# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: opencv setup
      uses: Dovyski/setup-opencv-action@v1.1
      with:
        # OpenCV version to be installed.
        opencv-version: 4.0.0 # default is 4.0.0
        install-deps: true
        opencv-extra-modules: false # optional, default is true
        GENERATE_PKGCONFIG: true # optional
    

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
